# Generated by Django 4.2.7 on 2023-11-18 03:10

import base.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="user",
            managers=[
                ("objects", base.models.CustomUserManager()),
            ],
        ),
    ]
