# Generated by Django 4.2.7 on 2023-11-18 19:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("base", "0002_alter_user_managers"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="avatar",
            field=models.ImageField(
                default="avatar.svg", null=True, upload_to="images/"
            ),
        ),
    ]
